name: cicd

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:

  ingest-etl-postprocess-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.3
      - name: install requirements
        run: just setup
      - name: ingest
        run: just ingest
        env:
          NVD_TOKEN: ${{ secrets.NVD_TOKEN }}
      - name: run ETL job
        run: just run
        continue-on-error: true 
      - name: postprocess
        run: just postprocess
